Project 3 add and remove
SamanAtashi/Best_To-Do-List pull request #4
Opened 2021-07-22 14:41 UTC by SamanAtashi

# Project 3: add and remove
Made with:
- HTML
- CSS
- JS
- WebPack

2021-07-22 16:01 UTC, Dipeshtwis requested changes
Hi @SamanAtashi, 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: Able to add and remove the task.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


 ## Required Changes ♻️

- [ ] I suggest that your pull request be more descriptive describing introduced changes in more details this is a recommended best practice as it makes reviewing easier.
- [x] All changes to the To Do List should be saved in local storage. currently no changes in happening in localstorage.

**_Also check the comments under the review_**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**_Check the comments under the review_**

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**_Dipesh Kumar_**


------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-22 16:01 UTC, Dipeshtwis commented on src/index.js
> +// eslint-disable-next-line import/no-cycle
[OPTIONAL]
- I can see you have disabled many rules in your project. I highly recommend to not disable many rules instead you can try to make your code good and follow the best practices. The purpose is to make your code better.

2021-07-22 16:01 UTC, Dipeshtwis commented on src/index.js
> +    }
- [ ]  Please use `localstorage` to store the data so that it persist after refresh as well.

2021-07-24 05:31 UTC, mricanho approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello @SamanAtashi  🔥 

You worked hard in all the instructions that the previous Code Reviewer gives you👍🏽 

![boomeasy](https://user-images.githubusercontent.com/60631456/126858496-3c10cf49-9c55-4107-95aa-6c7f6ca77b88.gif)

Now you can merge this branch 🚀 

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-26 10:27 UTC, merged